version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    versioning-strategy: increase
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "typescript-eslint"
      testing:
        patterns:
          - "vitest*"
          - "@vitest/*"
          - "@testing-library/*"
      react:
        patterns:
          - "react*"
          - "@types/react*"
      commitlint:
        patterns:
          - "@commitlint/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
